### ISSUE TITLE
Pen Paper Demo and RealSense tracking issues

### ISSUE THREAD

**Issue by giorgiounity** [DLR-RM/3DObjectTracking#38]
Hello @manuel-stoiber,
I'm testing your Pen and Paper Demo with a RealSense camera.
I've changed the the config.yaml file to use RealSense D435:
```
%YAML:1.2
RealSenseColorCamera:
  - name: color_camera
    metafile_path: config.yaml

RealSenseDepthCamera:
  - name: depth_camera
    metafile_path: config.yaml
```
I managed to have the algorithm tracking the Stabilo highlighter only once. Most of the times it's not tracking correctly.
I was wondering is this might be related to the RealSense D435? Is the demo supposed to work well with that sensor as well?
Should I change other parameters other than the sensor class?

(Basically, to start the tracking I just press 'X'? Is that correct?)
Thank you in advance,
Giorgio
