### ISSUE TITLE
Running the demo

### ISSUE THREAD

**Issue by FaiyazMeynikara** [DLR-RM/3DObjectTracking#55]
I am trying to run the run_pen_paper_demo.exe. I am getting the following error 
`Object color_camera in camera, FocusedSilhouetteRenderer does not exist.`  

These are the steps I followed,
I am trying to run the M3T application. I managed to install the dependencies and successfully take a CMake build. Then, I opened the solution in VS and successfully built and installed the project.  When I run the run_pen_paper_demo.exe , it force closes.

```
OS: Windows 10 64bit.
Build Type:  Release /64bit
```

Can we run the demo using a regular USB camera?

**Comment by futuyao** [comment]
I'm getting the same error with FocusedSilhouetteRenderer not found. Any update / solution on this? Thanks.

**Comment by AleTarsi** [comment]
I get exactly the same problem. Some update?

**Comment by tryzang** [comment]
Has this problem been solved?

**Comment by tryzang** [comment]
I also encountered the same problem

**Comment by MarioCavero** [comment]
Hey @CVtracker , did you have to modify anything else apart from the `config.yaml` file with 
```
RealSenseColorCamera:
  - name: color_camera
    metafile_path: config.yaml

RealSenseDepthCamera:
  - name: depth_camera
    metafile_path: config.yaml
instead of the azure part? 
```

I'm still getting 

`Object color_camera in camera, FocusedSilhouetteRenderer does not exist.`
