### ISSUE TITLE
Links get disconnected while tracking

### ISSUE THREAD

**Issue by libstr** [DLR-RM/3DObjectTracking#62]
Hi,

Firstly, Excellent work on the tracking system! 

I'm currently experiencing an issue with the link functionality. It seems that the links are getting disconnected during the tracking process. My understanding is that the child and parent links should remain attached irrespective of the real-world object?

Here is a blueprint of the links in the config file:

```
Link:
  - name: child_link
    metafile: child_link.yaml
    body: child
    modalities: [child_region_modality, child_texture_modality, child_depth_modality] 
  - name: parent_link
    metafile: parent_link.yaml
    body: parent
    modalities: [parent_region_modality, parent_texture_modality, parent_depth_modality] 
    child_links: [child_link]

Constraint:
  - name: constraint
    metafile: constraint.yaml
    link1: parent_link
    link2: child_link

Optimizer:
  - name: optimizer
    root_link: parent_link
    constraints: [constraint]
```

Could you let me know if I am missing something in my implementation?

I appreciate your support in addressing this issue.
Let me know if you need any further clarification or information.

Thank you,
